version: "3.8"

services:
  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/team_event
      - REDIS_URI=redis://redis:6379
    depends_on:
      - mongo
      - redis
    volumes:
      - ./backend:/app
    command: python app.py

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - ./database/init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
  mongo_data:
  redis_data:
